// Auto-generated by testbench-converter-plugin

import http from 'k6/http'
import {extractJSessionId, getHillaCsrfToken, getVaadinPushId, getVaadinSecurityKey, getVaadinUiId} from '../utils/vaadin-k6-helpers.js'
import { check, fail } from 'k6'
import { sleep } from 'k6'
import { SharedArray } from 'k6/data'
import { updateNodeMap, resolveNode } from '../utils/vaadin-k6-helpers.js'
import { textSummary } from '../utils/k6-summary.js'

export const options = {
  thresholds: {
    checks: [{ threshold: 'rate>=0.99', abortOnFail: true, delayAbortEval: '5s' }],
    http_req_duration: ['p(95)<2000', 'p(99)<5000'],
    'http_req_duration{name:edit-person: 1 GET /crud-example}': ['max>=0'],
    'http_req_duration{name:edit-person: 2 GET /VAADIN/build/indexhtml-CRBK0SRI.js}': ['max>=0'],
    'http_req_duration{name:edit-person: 3 GET /aura/aura.css}': ['max>=0'],
    'http_req_duration{name:edit-person: 4 GET /VAADIN/build/rolldown-runtime-8BhlS34s.js}': ['max>=0'],
    'http_req_duration{name:edit-person: 5 GET /VAADIN/build/frontend-DYOqZG7p.js}': ['max>=0'],
    'http_req_duration{name:edit-person: 6 GET /styles.css}': ['max>=0'],
    'http_req_duration{name:edit-person: 7 GET /aura/fonts/InstrumentSans/InstrumentSans.woff2}': ['max>=0'],
    'http_req_duration{name:edit-person: 8 GET init}': ['max>=0'],
    'http_req_duration{name:edit-person: 9 GET /VAADIN/build/FlowBootstrap-xhSPwkAC.js}': ['max>=0'],
    'http_req_duration{name:edit-person: 10 GET /VAADIN/build/generated-flow-imports-BIIPXANG.js}': ['max>=0'],
    'http_req_duration{name:edit-person: 11 GET /VAADIN/build/FlowClient-DVypvd1h.js}': ['max>=0'],
    'http_req_duration{name:edit-person: 12 GET /VAADIN/build/ApplicationConnection-DodrPk-H.js}': ['max>=0'],
    'http_req_duration{name:edit-person: 13 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 14 GET /edgedl/diffgen-puffin/ceofaddefefcbblgcgnibnonglccbfja/...}': ['max>=0'],
    'http_req_duration{name:edit-person: 15 GET /VAADIN/build/chunk-...-BaTzdjoW.js}': ['max>=0'],
    'http_req_duration{name:edit-person: 16 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 17 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 18 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 19 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 20 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 21 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 22 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 23 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 24 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 25 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 26 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 27 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 28 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 29 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 30 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 31 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 32 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 33 POST uidl}': ['max>=0'],
    'http_req_duration{name:edit-person: 34 POST uidl}': ['max>=0'],
  },
}


// Input test data from CSV — add rows to edit-person-data.csv for per-VU variation
function parseCsvRecords(text) {
  const records = [], n = text.length
  let i = 0
  function parseField() {
    if (i < n && text[i] === '"') {
      i++ // opening quote
      let f = ''
      while (i < n) {
        if (text[i] === '"' && text[i + 1] === '"') { f += '"'; i += 2 }
        else if (text[i] === '"') { i++; return f }
        else { f += text[i]; i++ }
      }
      return f
    }
    let f = ''
    while (i < n && text[i] !== ',' && text[i] !== '\r' && text[i] !== '\n') { f += text[i]; i++ }
    return f
  }
  while (i < n) {
    const row = []
    row.push(parseField())
    while (i < n && text[i] === ',') { i++; row.push(parseField()) }
    if (text[i] === '\r') i++
    if (text[i] === '\n') i++
    if (row.length > 1 || row[0] !== '') records.push(row)
  }
  return records
}

const inputData = new SharedArray('input data', function () {
  const records = parseCsvRecords(open('./edit-person-data.csv'))
  const headers = records[0]
  return records.slice(1).map(values => {
    const obj = {}
    headers.forEach((h, i) => obj[h.trim()] = (values[i] || '').trim())
    return obj
  })
})


// Server configuration - can be overridden with: k6 run -e APP_IP=192.168.1.100 -e APP_PORT=8081 script.js
const APP_IP = __ENV.APP_IP || 'localhost';
const APP_PORT = __ENV.APP_PORT || '8080';
const BASE_URL = `http://${APP_IP}:${APP_PORT}`;

export default function () {
  // Pick a random row from the input data CSV
  const inputRow = inputData[Math.floor(Math.random() * inputData.length)]

  // Request 1: GET http://localhost:8080/crud-example
  let response = http.get(
    `${BASE_URL}/crud-example`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"macOS"',
      'Upgrade-Insecure-Requests': '1',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
      'Sec-Fetch-Site': 'none',
      'Sec-Fetch-Mode': 'navigate',
      'Sec-Fetch-User': '?1',
      'Sec-Fetch-Dest': 'document',
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 1 GET /crud-example' }
    }
  )


// Extract JSESSIONID from Set-Cookie header
const jsessionId = extractJSessionId(response);
// Extract Hilla/Spring CSRF token from <meta name="_csrf"> in the HTML
const hillaCsrfToken = getHillaCsrfToken(response.body);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 1 GET /crud-example' })) {
    console.error(`edit-person: 1 GET /crud-example: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 122
  // Request 2: GET http://localhost:8080/VAADIN/build/indexhtml-CRBK0SRI.js
  response = http.get(
    `${BASE_URL}/VAADIN/build/indexhtml-CRBK0SRI.js`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'Origin': `${BASE_URL}`,
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'script',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 2 GET /VAADIN/build/indexhtml-CRBK0SRI.js' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 2 GET /VAADIN/build/indexhtml-CRBK0SRI.js' })) {
    console.error(`edit-person: 2 GET /VAADIN/build/indexhtml-CRBK0SRI.js: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 0
  // Request 3: GET http://localhost:8080/aura/aura.css?v-c=af4a6541
  response = http.get(
    `${BASE_URL}/aura/aura.css?v-c=af4a6541`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': 'text/css,*/*;q=0.1',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'no-cors',
      'Sec-Fetch-Dest': 'style',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 3 GET /aura/aura.css' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 3 GET /aura/aura.css' })) {
    console.error(`edit-person: 3 GET /aura/aura.css: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 1
  // Request 4: GET http://localhost:8080/VAADIN/build/rolldown-runtime-8BhlS34s.js
  response = http.get(
    `${BASE_URL}/VAADIN/build/rolldown-runtime-8BhlS34s.js`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'Origin': `${BASE_URL}`,
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'script',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 4 GET /VAADIN/build/rolldown-runtime-8BhlS34s.js' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 4 GET /VAADIN/build/rolldown-runtime-8BhlS34s.js' })) {
    console.error(`edit-person: 4 GET /VAADIN/build/rolldown-runtime-8BhlS34s.js: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 0
  // Request 5: GET http://localhost:8080/VAADIN/build/frontend-DYOqZG7p.js
  response = http.get(
    `${BASE_URL}/VAADIN/build/frontend-DYOqZG7p.js`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'Origin': `${BASE_URL}`,
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'script',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 5 GET /VAADIN/build/frontend-DYOqZG7p.js' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 5 GET /VAADIN/build/frontend-DYOqZG7p.js' })) {
    console.error(`edit-person: 5 GET /VAADIN/build/frontend-DYOqZG7p.js: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 0
  // Request 6: GET http://localhost:8080/styles.css?v-c=7fec18be
  response = http.get(
    `${BASE_URL}/styles.css?v-c=7fec18be`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': 'text/css,*/*;q=0.1',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'no-cors',
      'Sec-Fetch-Dest': 'style',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 6 GET /styles.css' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 6 GET /styles.css' })) {
    console.error(`edit-person: 6 GET /styles.css: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 119
  // Request 7: GET http://localhost:8080/aura/fonts/InstrumentSans/InstrumentSans.woff2
  response = http.get(
    `${BASE_URL}/aura/fonts/InstrumentSans/InstrumentSans.woff2`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'Origin': `${BASE_URL}`,
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'font',
      'Referer': `${BASE_URL}/aura/aura.css?v-c=af4a6541`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 7 GET /aura/fonts/InstrumentSans/InstrumentSans.woff2' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 7 GET /aura/fonts/InstrumentSans/InstrumentSans.woff2' })) {
    console.error(`edit-person: 7 GET /aura/fonts/InstrumentSans/InstrumentSans.woff2: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 13
  // Request 8: GET http://localhost:8080/?v-r=init&location=crud-example&query=&v-sh=600&v-sw=80...
  response = http.get(
    `${BASE_URL}/?v-r=init&location=crud-example&query=&v-sh=600&v-sw=800&v-wh=413&v-ww=756&v-bh=413&v-bw=756&v-curdate=1790671704434&v-tzo=-120&v-dstd=60&v-rtzo=-60&v-dston=true&v-tzid=Europe%2FBerlin&v-wn=v-0.8778000407995855&v-td=false&v-pr=1&v-np=MacIntel&v-cs=&v-pv=VISIBLE&v-fs=NOT_FULLSCREEN&v-so=landscape-primary&v-soa=0&v-tn=aura&v-ga=GRANTED&v-wla=SUPPORTED&v-ws=true`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 8 GET init' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 8 GET init' })) {
    console.error(`edit-person: 8 GET init: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  var body = response.body || ''
  // Abort iteration and trigger test abort if init response is invalid
  if (!check(response, {
    'init request succeeded': (r) => r.status === 200,
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'valid init response': (r) => (r.body || '').includes('"v-uiId"') && (r.body || '').includes('"Vaadin-Security-Key"'),
  })) {
    fail(`Request 8 (GET http://localhost:8080/?v-r=init&location=crud-example&query=&v-sh=600&v-sw=80...): init failed (status ${response.status}): ${body.substring(0, 200)}`)

// Think time: user reading the page
sleep(2.0 + Math.random() * 3.0);
  }

  // Extract Vaadin session values from init response
  let uiId = body.match(/"v-uiId"\s*:\s*(\d+)/)[1]
  let csrfToken = body.match(/"Vaadin-Security-Key"\s*:\s*"([^"]+)"/)[1]
  let syncId = 0
  let clientId = 0
  let gridKeys = []
  let selectedKey = '0'
  let nodeMap = {}
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 264
  // Request 9: GET http://localhost:8080/VAADIN/build/FlowBootstrap-xhSPwkAC.js
  response = http.get(
    `${BASE_URL}/VAADIN/build/FlowBootstrap-xhSPwkAC.js`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'Origin': `${BASE_URL}`,
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'script',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 9 GET /VAADIN/build/FlowBootstrap-xhSPwkAC.js' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 9 GET /VAADIN/build/FlowBootstrap-xhSPwkAC.js' })) {
    console.error(`edit-person: 9 GET /VAADIN/build/FlowBootstrap-xhSPwkAC.js: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 10
  // Request 10: GET http://localhost:8080/VAADIN/build/generated-flow-imports-BIIPXANG.js
  response = http.get(
    `${BASE_URL}/VAADIN/build/generated-flow-imports-BIIPXANG.js`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'Origin': `${BASE_URL}`,
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'script',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 10 GET /VAADIN/build/generated-flow-imports-BIIPXANG.js' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 10 GET /VAADIN/build/generated-flow-imports-BIIPXANG.js' })) {
    console.error(`edit-person: 10 GET /VAADIN/build/generated-flow-imports-BIIPXANG.js: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 18
  // Request 11: GET http://localhost:8080/VAADIN/build/FlowClient-DVypvd1h.js
  response = http.get(
    `${BASE_URL}/VAADIN/build/FlowClient-DVypvd1h.js`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'Origin': `${BASE_URL}`,
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'script',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 11 GET /VAADIN/build/FlowClient-DVypvd1h.js' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 11 GET /VAADIN/build/FlowClient-DVypvd1h.js' })) {
    console.error(`edit-person: 11 GET /VAADIN/build/FlowClient-DVypvd1h.js: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 9
  // Request 12: GET http://localhost:8080/VAADIN/build/ApplicationConnection-DodrPk-H.js
  response = http.get(
    `${BASE_URL}/VAADIN/build/ApplicationConnection-DodrPk-H.js`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'Origin': `${BASE_URL}`,
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'script',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 12 GET /VAADIN/build/ApplicationConnection-DodrPk-H.js' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 12 GET /VAADIN/build/ApplicationConnection-DodrPk-H.js' })) {
    console.error(`edit-person: 12 GET /VAADIN/build/ApplicationConnection-DodrPk-H.js: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 17
  // Request 13: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  /* unresolved node 1 */
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":1,"event":"ui-navigate","data":{"route":"/crud-example","query":"","appShellTitle":"","historyState":{"idx":0},"trigger":""}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 13 POST uidl' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 13 POST uidl' })) {
    console.error(`edit-person: 13 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 13 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 84
  // Request 14: GET http://edgedl.me.gvt1.com/edgedl/diffgen-puffin/ceofaddefefcbblgcgnibnonglccb...
  response = http.get(
    'http://edgedl.me.gvt1.com/edgedl/diffgen-puffin/ceofaddefefcbblgcgnibnonglccbfja/fbdd96f424c67bd94b857b415c88a5711d0711f4d7a62d733ee650e5afe87766',
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36'
    },
      tags: { name: 'edit-person: 14 GET /edgedl/diffgen-puffin/ceofaddefefcbblgcgnibnonglccbfja/...' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 14 GET /edgedl/diffgen-puffin/ceofaddefefcbblgcgnibnonglccbfja/...' })) {
    console.error(`edit-person: 14 GET /edgedl/diffgen-puffin/ceofaddefefcbblgcgnibnonglccbfja/...: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 307
  // Request 15: GET http://localhost:8080/VAADIN/build/chunk-c9032f74a02a9eb2d9d0dc21b6f2c6b4c134...
  response = http.get(
    `${BASE_URL}/VAADIN/build/chunk-c9032f74a02a9eb2d9d0dc21b6f2c6b4c134b1cfc03eede290b534b2b8b21d87-BaTzdjoW.js`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'Origin': `${BASE_URL}`,
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'script',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 15 GET /VAADIN/build/chunk-...-BaTzdjoW.js' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 15 GET /VAADIN/build/chunk-...-BaTzdjoW.js' })) {
    console.error(`edit-person: 15 GET /VAADIN/build/chunk-...-BaTzdjoW.js: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // HAR_DELTA_MS: 50
  // Request 16: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":${resolveNode(nodeMap, 'vaadin-date-picker#1')},"event":"value-changed","data":{}},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-checkbox#1')},"event":"checked-changed","data":{}},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-checkbox#1')},"event":"indeterminate-changed","data":{}},{"type":"publishedEventHandler","node":${resolveNode(nodeMap, 'vaadin-grid#1')},"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[0],"promise":0}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 16 POST uidl' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 16 POST uidl' })) {
    console.error(`edit-person: 16 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 16 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 132
  // Request 17: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":${resolveNode(nodeMap, 'vaadin-text-field#6')},"feature":1,"property":"value","value":"${inputRow.input_1}"},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-text-field#6')},"event":"change","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 17 POST uidl' }
    }
  )

// Think time: user thinking before next action
sleep(0.5 + Math.random() * 1.5);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 17 POST uidl' })) {
    console.error(`edit-person: 17 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 17 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 81
  // Request 18: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":${resolveNode(nodeMap, 'lastname-field')},"feature":1,"property":"value","value":"${inputRow.input_2}"},{"type":"event","node":${resolveNode(nodeMap, 'lastname-field')},"event":"change","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 18 POST uidl' }
    }
  )

// Think time: user thinking before next action
sleep(0.5 + Math.random() * 1.5);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 18 POST uidl' })) {
    console.error(`edit-person: 18 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 18 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 70
  // Request 19: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":${resolveNode(nodeMap, 'vaadin-text-field#4')},"feature":1,"property":"value","value":"${inputRow.input_3}"},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-text-field#4')},"event":"change","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 19 POST uidl' }
    }
  )

// Think time: user thinking before next action
sleep(0.5 + Math.random() * 1.5);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 19 POST uidl' })) {
    console.error(`edit-person: 19 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 19 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 77
  // Request 20: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":${resolveNode(nodeMap, 'vaadin-text-field#3')},"feature":1,"property":"value","value":"${inputRow.input_4}"},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-text-field#3')},"event":"change","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 20 POST uidl' }
    }
  )

// Think time: user thinking before next action
sleep(0.5 + Math.random() * 1.5);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 20 POST uidl' })) {
    console.error(`edit-person: 20 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 20 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 35
  // Request 21: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":${resolveNode(nodeMap, 'vaadin-date-picker#1')},"feature":1,"property":"value","value":"${inputRow.input_5}"},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-date-picker#1')},"event":"value-changed","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 21 POST uidl' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 21 POST uidl' })) {
    console.error(`edit-person: 21 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 21 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 77
  // Request 22: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":${resolveNode(nodeMap, 'vaadin-text-field#2')},"feature":1,"property":"value","value":"${inputRow.input_6}"},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-text-field#2')},"event":"change","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 22 POST uidl' }
    }
  )

// Think time: user thinking before next action
sleep(0.5 + Math.random() * 1.5);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 22 POST uidl' })) {
    console.error(`edit-person: 22 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 22 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 63
  // Request 23: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":${resolveNode(nodeMap, 'vaadin-text-field#1')},"feature":1,"property":"value","value":"${inputRow.input_7}"},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-text-field#1')},"event":"change","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 23 POST uidl' }
    }
  )

// Think time: user thinking before next action
sleep(0.5 + Math.random() * 1.5);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 23 POST uidl' })) {
    console.error(`edit-person: 23 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 23 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 34
  // Request 24: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":${resolveNode(nodeMap, 'vaadin-checkbox#1')},"feature":1,"property":"checked","value":true},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-checkbox#1')},"event":"checked-changed","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 24 POST uidl' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 24 POST uidl' })) {
    console.error(`edit-person: 24 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 24 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 47
  // Request 25: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":${resolveNode(nodeMap, 'save-button')},"event":"click","data":{"event.shiftKey":false,"event.metaKey":false,"event.detail":0,"event.ctrlKey":false,"event.clientX":0,"event.clientY":0,"event.altKey":false,"event.button":0,"event.screenY":0,"event.screenX":0}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 25 POST uidl' }
    }
  )

// Think time: user thinking before next action
sleep(0.5 + Math.random() * 1.5);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 25 POST uidl' })) {
    console.error(`edit-person: 25 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 25 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 91
  // Request 26: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":${resolveNode(nodeMap, 'vaadin-notification#1')},"event":"opened-changed","data":{}},{"type":"publishedEventHandler","node":${resolveNode(nodeMap, 'vaadin-grid#1')},"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[1],"promise":1}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 26 POST uidl' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 26 POST uidl' })) {
    console.error(`edit-person: 26 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 26 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 232
  // Request 27: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"mSync","node":${resolveNode(nodeMap, 'vaadin-text-field#1')},"feature":1,"property":"value","value":"${inputRow.input_8}"},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-text-field#1')},"event":"change","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example/4000/edit`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 27 POST uidl' }
    }
  )

// Think time: user thinking before next action
sleep(0.5 + Math.random() * 1.5);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 27 POST uidl' })) {
    console.error(`edit-person: 27 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 27 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 58
  // Request 28: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":${resolveNode(nodeMap, 'save-button')},"event":"click","data":{"event.shiftKey":false,"event.metaKey":false,"event.detail":0,"event.ctrlKey":false,"event.clientX":0,"event.clientY":0,"event.altKey":false,"event.button":0,"event.screenY":0,"event.screenX":0}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example/4000/edit`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 28 POST uidl' }
    }
  )

// Think time: user thinking before next action
sleep(0.5 + Math.random() * 1.5);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 28 POST uidl' })) {
    console.error(`edit-person: 28 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 28 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 55
  // Request 29: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":${resolveNode(nodeMap, 'vaadin-notification#2')},"event":"opened-changed","data":{}},{"type":"publishedEventHandler","node":${resolveNode(nodeMap, 'vaadin-grid#1')},"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[2],"promise":2}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example/4000/edit`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 29 POST uidl' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 29 POST uidl' })) {
    console.error(`edit-person: 29 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 29 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 140
  // Request 30: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":${resolveNode(nodeMap, 'delete-button')},"event":"click","data":{"event.shiftKey":false,"event.metaKey":false,"event.detail":0,"event.ctrlKey":false,"event.clientX":0,"event.clientY":0,"event.altKey":false,"event.button":0,"event.screenY":0,"event.screenX":0}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example/4000/edit`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 30 POST uidl' }
    }
  )

// Think time: user thinking before next action
sleep(0.5 + Math.random() * 1.5);

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 30 POST uidl' })) {
    console.error(`edit-person: 30 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 30 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 20
  // Request 31: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":${resolveNode(nodeMap, 'vaadin-confirm-dialog#1')},"event":"opened-changed","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example/4000/edit`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 31 POST uidl' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 31 POST uidl' })) {
    console.error(`edit-person: 31 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 31 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 49
  // Request 32: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":${resolveNode(nodeMap, 'vaadin-confirm-dialog#1')},"event":"confirm"},{"type":"mSync","node":${resolveNode(nodeMap, 'vaadin-confirm-dialog#1')},"feature":1,"property":"opened","value":false},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-confirm-dialog#1')},"event":"opened-changed","data":{}}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example/4000/edit`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 32 POST uidl' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 32 POST uidl' })) {
    console.error(`edit-person: 32 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 32 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 52
  // Request 33: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":${resolveNode(nodeMap, 'vaadin-notification#3')},"event":"opened-changed","data":{}},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-date-picker#1')},"event":"value-changed","data":{}},{"type":"event","node":${resolveNode(nodeMap, 'vaadin-checkbox#1')},"event":"checked-changed","data":{}},{"type":"publishedEventHandler","node":${resolveNode(nodeMap, 'vaadin-grid#1')},"templateEventMethodName":"confirmUpdate","templateEventMethodArgs":[3],"promise":3}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example/4000/edit`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 33 POST uidl' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 33 POST uidl' })) {
    console.error(`edit-person: 33 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 33 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

  // HAR_DELTA_MS: 128
  // Request 34: POST http://localhost:8080/?v-r=uidl&v-uiId=0
  response = http.post(
    `${BASE_URL}/?v-r=uidl&v-uiId=${uiId}`,
    `{"csrfToken":"${csrfToken}","rpc":[{"type":"event","node":${resolveNode(nodeMap, 'vaadin-confirm-dialog#1')},"event":"closed"}],"syncId":${syncId},"clientId":${clientId}}`,
    {
      headers: {
      'Proxy-Connection': 'keep-alive',
      'sec-ch-ua-platform': '"macOS"',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/154.0.0.0 Safari/537.36',
      'sec-ch-ua': '"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"',
      'Content-Type': 'application/json; charset=UTF-8',
      'sec-ch-ua-mobile': '?0',
      'Accept': '*/*',
      'Origin': `${BASE_URL}`,
      'Sec-Fetch-Site': 'same-origin',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': `${BASE_URL}/crud-example`,
      'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8'
    },
      tags: { name: 'edit-person: 34 POST uidl' }
    }
  )

  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: 'edit-person: 34 POST uidl' })) {
    console.error(`edit-person: 34 POST uidl: HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)
  }

  // Abort iteration and trigger test abort if UIDL response is invalid
  var body = response.body || ''
  var syncIdMatch = body.match(/"syncId"\s*:\s*(-?\d+)/)
  if (!check(response, {
    'UIDL request succeeded': (r) => r.status === 200,
    'no server error': (r) => !(r.body || '').includes('"appError"'),
    'no exception': (r) => !(r.body || '').includes('Exception'),
    'session is valid': (r) => !(r.body || '').includes('Your session needs to be refreshed'),
    'security key valid': (r) => !(r.body || '').includes('Invalid security key'),
    'valid UIDL response': () => syncIdMatch !== null,
  })) {
    fail(`Request 34 (POST http://localhost:8080/?v-r=uidl&v-uiId=0): UIDL failed (status ${response.status}): ${body.substring(0, 200)}`)
  }

  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)
  syncId = Math.max(0, parseInt(syncIdMatch[1]))
  clientId++
  // Extract grid item keys from response (used for select/edit operations).
  // Anchor on object-start so only the first key in a row matches; change-record
  // keys (e.g. type+key+value triples) are preceded by other fields and skipped.
  var found = body.match(/\x7B"key":"[^"]+"/g)
  if (found) gridKeys = found.map(s => s.split('"')[3])
  nodeMap = updateNodeMap(nodeMap, response.body)

}

export function handleSummary(data) {
  // Compact console summary — keep only the headline metrics.
  // Full metric set (including per-request sub-metrics) still
  // goes to the JSON file when SUMMARY_FILE is set.
  const keepMetrics = new Set([
    'checks', 'http_req_duration', 'http_req_failed',
    'http_reqs', 'iterations',
  ])
  const consoleData = Object.assign({}, data, {
    metrics: Object.fromEntries(
      Object.entries(data.metrics).filter(([key]) => keepMetrics.has(key))
    )
  })
  const result = {
    'stdout': textSummary(consoleData, { indent: ' ', enableColors: true }),
  }
  if (__ENV.SUMMARY_FILE) {
    result[__ENV.SUMMARY_FILE] = JSON.stringify(data, null, 2)
  }
  return result
}